files:
  - source: Patch-pack-original
    ignore:
      - simplyswords
    translation: Patch-Pack-CN/%original_path%/zh_cn.json
  - source: Patch-pack-original/config/paxi/datapacks/vm/data
    translation: '%original_path%'
