files:
  - source: Patch-pack-original/config/paxi/resourcepacks/vm-language/assets
    ignore:
      - Patch-pack-original/config/paxi/datapacks
    translation: '%original_path%/zh_cn.json'
  - source: Patch-pack-original/config/paxi/datapacks/vm/data/rpg_origins
    translation: '%original_path%/%original_file_name%'
