files:
  - source: config/paxi/resourcepacks/vm-language/assets
    ignore:
      - simplyswords
    translation: '%original_path%/zh_cn.json'
  - source: config/paxi/datapacks/vm/data
    translation: '%original_path%'
